site_name: MPS Developer's Guide
pages:
  - Main Page: index.md
  - Android:
    - Project Setup: 'android/index.md'
    - SDK Initialization: 'android/2_sdk_init.md'
    - Request Banner Programmatically: 'android/3_request_banner_programmatically.md'
    - Request Banner with XML: 'android/4_banner_xml.md'
    - Request Interstitial Ad: 'android/5_interstitial.md'
    - Test App & Installation: 'android/6_test_app.md'
    - Javadoc: 'android/javadocs.md'
  - iOS:
    - Project Setup: 'ios/1 Project setup.md'
    - SDK Initialization: 'ios/2 SDK Initialization.md'
    - Request Banner Programmatically: 'ios/3 Request Banner Programmatically.md'
    - Request Banner with Storyboard: 'ios/4 Request Banner with Storyboard.md'
    - Request Interstitial Ad: 'ios/5 Request Interstitial Ad.md'
    - Additional Functionality: 'ios/6 Additional Functionality.md'
    - Test App & Installation: 'ios/7 Test App & Installation.md'
theme_dir: readthedocs
use_directory_urls: false